<#
.SYNOPSIS
    Validates Key Vault and Policy CSV data quality

.DESCRIPTION
    Validates CSV files generated by Get-KeyVaultInventory.ps1 and Get-PolicyAssignmentInventory.ps1
    to ensure all critical fields are populated and data is suitable for production use.

.PARAMETER KeyVaultCSV
    Path to KeyVaultInventory CSV file

.PARAMETER PolicyCSV
    Path to PolicyAssignmentInventory CSV file

.PARAMETER OutputReport
    Path where validation report will be saved (default: CSV-Validation-Report.txt in same directory as KeyVaultCSV)

.EXAMPLE
    .\Validate-CSVDataQuality.ps1 -KeyVaultCSV ".\KeyVaultInventory.csv" -PolicyCSV ".\PolicyAssignmentInventory.csv"

.EXAMPLE
    .\Validate-CSVDataQuality.ps1 `
        -KeyVaultCSV ".\TestResults-AAD\KeyVaultInventory.csv" `
        -PolicyCSV ".\TestResults-AAD\PolicyAssignmentInventory.csv" `
        -OutputReport ".\TestResults-AAD\CSV-Validation-Report.txt"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateScript({ Test-Path $_ -PathType Leaf })]
    [string]$KeyVaultCSV,
    
    [Parameter(Mandatory)]
    [ValidateScript({ Test-Path $_ -PathType Leaf })]
    [string]$PolicyCSV,
    
    [Parameter()]
    [string]$OutputReport
)

# Determine output report path
if (-not $OutputReport) {
    $kvDir = Split-Path -Parent $KeyVaultCSV
    $OutputReport = Join-Path $kvDir "CSV-Validation-Report.txt"
}

# Initialize error tracking
$errors = @()
$warnings = @()

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "CSV DATA QUALITY VALIDATION" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

# ====================================
# Validate Key Vault CSV
# ====================================
Write-Host "Validating Key Vault Inventory CSV..." -ForegroundColor Cyan
Write-Host "  File: $KeyVaultCSV`n" -ForegroundColor Gray

$kvData = Import-Csv $KeyVaultCSV
$kvFileSize = (Get-Item $KeyVaultCSV).Length
$kvFileSizeKB = [math]::Round($kvFileSize / 1KB, 1)

Write-Host "  Total Records: $($kvData.Count)" -ForegroundColor White
Write-Host "  File Size: $kvFileSizeKB KB`n" -ForegroundColor White

# Check critical fields
$nullKVNames = @($kvData | Where-Object { [string]::IsNullOrWhiteSpace($_.KeyVaultName) }).Count
$nullLocations = @($kvData | Where-Object { [string]::IsNullOrWhiteSpace($_.Location) }).Count
$nullRGs = @($kvData | Where-Object { [string]::IsNullOrWhiteSpace($_.ResourceGroupName) }).Count
$nullSubscriptions = @($kvData | Where-Object { [string]::IsNullOrWhiteSpace($_.SubscriptionName) }).Count

Write-Host "  CRITICAL FIELD VALIDATION:" -ForegroundColor Yellow

# KeyVaultName validation
if ($nullKVNames -gt 0) {
    $errors += "CRITICAL: $nullKVNames records ($(($nullKVNames/$kvData.Count*100).ToString('0.0'))%) missing KeyVaultName"
    Write-Host "    ❌ KeyVaultName: $nullKVNames empty records (FAIL)" -ForegroundColor Red
} else {
    Write-Host "    ✅ KeyVaultName: All $($kvData.Count) records populated (PASS)" -ForegroundColor Green
}

# Location validation
if ($nullLocations -gt 0) {
    $errors += "CRITICAL: $nullLocations records ($(($nullLocations/$kvData.Count*100).ToString('0.0'))%) missing Location"
    Write-Host "    ❌ Location: $nullLocations empty records (FAIL)" -ForegroundColor Red
} else {
    Write-Host "    ✅ Location: All $($kvData.Count) records populated (PASS)" -ForegroundColor Green
}

# ResourceGroupName validation
if ($nullRGs -gt 0) {
    $warnings += "WARNING: $nullRGs records ($(($nullRGs/$kvData.Count*100).ToString('0.0'))%) missing ResourceGroupName"
    Write-Host "    ⚠️  ResourceGroupName: $nullRGs empty records (WARN)" -ForegroundColor Yellow
} else {
    Write-Host "    ✅ ResourceGroupName: All $($kvData.Count) records populated (PASS)" -ForegroundColor Green
}

# SubscriptionName validation
if ($nullSubscriptions -gt 0) {
    $errors += "CRITICAL: $nullSubscriptions records ($(($nullSubscriptions/$kvData.Count*100).ToString('0.0'))%) missing SubscriptionName"
    Write-Host "    ❌ SubscriptionName: $nullSubscriptions empty records (FAIL)" -ForegroundColor Red
} else {
    Write-Host "    ✅ SubscriptionName: All $($kvData.Count) records populated (PASS)" -ForegroundColor Green
}

# Compliance statistics
Write-Host "`n  COMPLIANCE STATISTICS:" -ForegroundColor Yellow
$softDeleteEnabled = @($kvData | Where-Object { $_.EnableSoftDelete -eq 'True' }).Count
$purgeProtectionEnabled = @($kvData | Where-Object { $_.EnablePurgeProtection -eq 'True' }).Count
$rbacEnabled = @($kvData | Where-Object { $_.EnableRbacAuthorization -eq 'True' }).Count
$publicNetworkDisabled = @($kvData | Where-Object { $_.PublicNetworkAccess -eq 'Disabled' }).Count
$privateEndpoints = @($kvData | Where-Object { $_.PrivateEndpointConnections -ne 'Not configured' }).Count

Write-Host "    - Soft Delete Enabled: $softDeleteEnabled vaults ($(($softDeleteEnabled/$kvData.Count*100).ToString('0.0'))%)" -ForegroundColor Gray
Write-Host "    - Purge Protection Enabled: $purgeProtectionEnabled vaults ($(($purgeProtectionEnabled/$kvData.Count*100).ToString('0.0'))%)" -ForegroundColor Gray
Write-Host "    - RBAC Authorization Enabled: $rbacEnabled vaults ($(($rbacEnabled/$kvData.Count*100).ToString('0.0'))%)" -ForegroundColor Gray
Write-Host "    - Public Network Disabled: $publicNetworkDisabled vaults ($(($publicNetworkDisabled/$kvData.Count*100).ToString('0.0'))%)" -ForegroundColor Gray
Write-Host "    - Private Endpoints Configured: $privateEndpoints vaults ($(($privateEndpoints/$kvData.Count*100).ToString('0.0'))%)" -ForegroundColor Gray

# Location distribution (top 10)
Write-Host "`n  TOP 10 LOCATIONS:" -ForegroundColor Yellow
$locationStats = $kvData | Where-Object { -not [string]::IsNullOrWhiteSpace($_.Location) } | 
    Group-Object -Property Location | 
    Sort-Object -Property Count -Descending | 
    Select-Object -First 10

foreach ($loc in $locationStats) {
    Write-Host "    - $($loc.Name): $($loc.Count) vaults" -ForegroundColor Gray
}

# ====================================
# Validate Policy CSV
# ====================================
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "Validating Policy Assignment Inventory CSV..." -ForegroundColor Cyan
Write-Host "  File: $PolicyCSV`n" -ForegroundColor Gray

$policyData = Import-Csv $PolicyCSV
$policyFileSize = (Get-Item $PolicyCSV).Length
$policyFileSizeMB = [math]::Round($policyFileSize / 1MB, 1)

Write-Host "  Total Records: $($policyData.Count)" -ForegroundColor White
Write-Host "  File Size: $policyFileSizeMB MB`n" -ForegroundColor White

# Check critical fields (NOTE: CSV uses AssignmentName and DisplayName, not PolicyAssignmentId and PolicyDisplayName)
$nullAssignments = @($policyData | Where-Object { [string]::IsNullOrWhiteSpace($_.AssignmentName) }).Count
$nullDisplayNames = @($policyData | Where-Object { [string]::IsNullOrWhiteSpace($_.DisplayName) }).Count
$nullScopes = @($policyData | Where-Object { [string]::IsNullOrWhiteSpace($_.Scope) }).Count
$nullSubscriptionNames = @($policyData | Where-Object { [string]::IsNullOrWhiteSpace($_.SubscriptionName) }).Count

Write-Host "  CRITICAL FIELD VALIDATION:" -ForegroundColor Yellow

# AssignmentName validation
if ($nullAssignments -gt 0) {
    $errors += "CRITICAL: $nullAssignments policy records ($(($nullAssignments/$policyData.Count*100).ToString('0.0'))%) missing AssignmentName"
    Write-Host "    ❌ AssignmentName: $nullAssignments empty records (FAIL)" -ForegroundColor Red
} else {
    Write-Host "    ✅ AssignmentName: All $($policyData.Count) records populated (PASS)" -ForegroundColor Green
}

# DisplayName validation (warnings only - some built-in policies may not have display names)
if ($nullDisplayNames -gt 0) {
    $warnings += "INFO: $nullDisplayNames policy records ($(($nullDisplayNames/$policyData.Count*100).ToString('0.0'))%) missing DisplayName (likely built-in policies)"
    Write-Host "    ⚠️  DisplayName: $nullDisplayNames empty records (WARN - may be built-in policies)" -ForegroundColor Yellow
} else {
    Write-Host "    ✅ DisplayName: All $($policyData.Count) records populated (PASS)" -ForegroundColor Green
}

# Scope validation
if ($nullScopes -gt 0) {
    $errors += "CRITICAL: $nullScopes policy records ($(($nullScopes/$policyData.Count*100).ToString('0.0'))%) missing Scope"
    Write-Host "    ❌ Scope: $nullScopes empty records (FAIL)" -ForegroundColor Red
} else {
    Write-Host "    ✅ Scope: All $($policyData.Count) records populated (PASS)" -ForegroundColor Green
}

# SubscriptionName validation
if ($nullSubscriptionNames -gt 0) {
    # Management group scoped policies won't have subscription names - this is expected
    $mgScopedPolicies = @($policyData | Where-Object { $_.Scope -like '/providers/Microsoft.Management/managementGroups/*' }).Count
    if ($nullSubscriptionNames -eq $mgScopedPolicies) {
        Write-Host "    ✅ SubscriptionName: $nullSubscriptionNames empty (all are management group scoped - PASS)" -ForegroundColor Green
    } else {
        $warnings += "WARNING: $nullSubscriptionNames policy records missing SubscriptionName (expected $mgScopedPolicies for MG-scoped)"
        Write-Host "    ⚠️  SubscriptionName: $nullSubscriptionNames empty records (WARN)" -ForegroundColor Yellow
    }
} else {
    Write-Host "    ✅ SubscriptionName: All $($policyData.Count) records populated (PASS)" -ForegroundColor Green
}

# Policy statistics
Write-Host "`n  POLICY STATISTICS:" -ForegroundColor Yellow

# Scope breakdown
$subscriptionScoped = @($policyData | Where-Object { $_.Scope -like '/subscriptions/*' -and $_.Scope -notlike '*/resourceGroups/*' }).Count
$mgScoped = @($policyData | Where-Object { $_.Scope -like '/providers/Microsoft.Management/managementGroups/*' }).Count
$rgScoped = @($policyData | Where-Object { $_.Scope -like '*/resourceGroups/*' }).Count

Write-Host "    - Subscription Scope: $subscriptionScoped assignments ($(($subscriptionScoped/$policyData.Count*100).ToString('0.0'))%)" -ForegroundColor Gray
Write-Host "    - Management Group Scope: $mgScoped assignments ($(($mgScoped/$policyData.Count*100).ToString('0.0'))%)" -ForegroundColor Gray
Write-Host "    - Resource Group Scope: $rgScoped assignments ($(($rgScoped/$policyData.Count*100).ToString('0.0'))%)" -ForegroundColor Gray

# Enforcement mode breakdown
$enforced = @($policyData | Where-Object { $_.EnforcementMode -eq 'Default' }).Count
$notEnforced = @($policyData | Where-Object { $_.EnforcementMode -eq 'DoNotEnforce' }).Count

Write-Host "`n    - Enforced (Default): $enforced assignments ($(($enforced/$policyData.Count*100).ToString('0.0'))%)" -ForegroundColor Gray
Write-Host "    - Not Enforced (DoNotEnforce): $notEnforced assignments ($(($notEnforced/$policyData.Count*100).ToString('0.0'))%)" -ForegroundColor Gray

# Key Vault policies
$kvPolicies = @($policyData | Where-Object { $_.DisplayName -like '*Key Vault*' -or $_.DisplayName -like '*key vault*' }).Count
$uniqueKVPolicies = @($policyData | Where-Object { $_.DisplayName -like '*Key Vault*' -or $_.DisplayName -like '*key vault*' } | 
    Select-Object -Property DisplayName -Unique).Count

Write-Host "`n    - Key Vault-Related Policies: $kvPolicies assignments" -ForegroundColor Gray
Write-Host "    - Unique Key Vault Policies: $uniqueKVPolicies policy types" -ForegroundColor Gray

# ====================================
# Overall Status
# ====================================
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "VALIDATION SUMMARY" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

if ($errors.Count -eq 0 -and $warnings.Count -eq 0) {
    Write-Host "✅ OVERALL STATUS: PASS" -ForegroundColor Green
    Write-Host "`nAll critical fields populated, CSVs ready for production use." -ForegroundColor Green
    $overallStatus = "PASS"
} elseif ($errors.Count -eq 0) {
    Write-Host "⚠️  OVERALL STATUS: PASS WITH WARNINGS" -ForegroundColor Yellow
    Write-Host "`nWarnings Found ($($warnings.Count)):" -ForegroundColor Yellow
    $warnings | ForEach-Object { Write-Host "  - $_" -ForegroundColor Yellow }
    Write-Host "`nCSVs are usable but review warnings above." -ForegroundColor Yellow
    $overallStatus = "PASS (with warnings)"
} else {
    Write-Host "❌ OVERALL STATUS: FAIL" -ForegroundColor Red
    Write-Host "`nCritical Errors Found ($($errors.Count)):" -ForegroundColor Red
    $errors | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    if ($warnings.Count -gt 0) {
        Write-Host "`nWarnings ($($warnings.Count)):" -ForegroundColor Yellow
        $warnings | ForEach-Object { Write-Host "  - $_" -ForegroundColor Yellow }
    }
    Write-Host "`n❌ CSVs NOT suitable for production use - fix data collection script" -ForegroundColor Red
    $overallStatus = "FAIL"
}

Write-Host "`n========================================`n" -ForegroundColor Cyan

# ====================================
# Generate Report File
# ====================================
$reportContent = @"
========================================
CSV DATA QUALITY VALIDATION REPORT
========================================
Test Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
Script Version: 1.0.0

KEY VAULT INVENTORY CSV:
  File: $KeyVaultCSV
  Total Records: $($kvData.Count)
  File Size: $kvFileSizeKB KB
  
  CRITICAL FIELD VALIDATION:
$(if ($nullKVNames -eq 0) { "  ✅ KeyVaultName: 0 null records (PASS)" } else { "  ❌ KeyVaultName: $nullKVNames null records ($([math]::Round($nullKVNames/$kvData.Count*100,1))%) (FAIL)" })
$(if ($nullLocations -eq 0) { "  ✅ Location: 0 null records (PASS)" } else { "  ❌ Location: $nullLocations null records ($([math]::Round($nullLocations/$kvData.Count*100,1))%) (FAIL)" })
$(if ($nullRGs -eq 0) { "  ✅ ResourceGroupName: 0 null records (PASS)" } else { "  ⚠️  ResourceGroupName: $nullRGs null records ($([math]::Round($nullRGs/$kvData.Count*100,1))%) (WARN)" })
$(if ($nullSubscriptions -eq 0) { "  ✅ SubscriptionName: 0 null records (PASS)" } else { "  ❌ SubscriptionName: $nullSubscriptions null records ($([math]::Round($nullSubscriptions/$kvData.Count*100,1))%) (FAIL)" })
  
  COMPLIANCE STATISTICS:
  - Soft Delete Enabled: $softDeleteEnabled vaults ($([math]::Round($softDeleteEnabled/$kvData.Count*100,1))%)
  - Purge Protection Enabled: $purgeProtectionEnabled vaults ($([math]::Round($purgeProtectionEnabled/$kvData.Count*100,1))%)
  - RBAC Authorization Enabled: $rbacEnabled vaults ($([math]::Round($rbacEnabled/$kvData.Count*100,1))%)
  - Public Network Disabled: $publicNetworkDisabled vaults ($([math]::Round($publicNetworkDisabled/$kvData.Count*100,1))%)
  - Private Endpoints Configured: $privateEndpoints vaults ($([math]::Round($privateEndpoints/$kvData.Count*100,1))%)

  TOP 10 LOCATIONS:
$($locationStats | ForEach-Object { "    $($_.Name): $($_.Count) vaults" } | Out-String)

POLICY ASSIGNMENT INVENTORY CSV:
  File: $PolicyCSV
  Total Records: $($policyData.Count)
  File Size: $policyFileSizeMB MB
  
  CRITICAL FIELD VALIDATION:
$(if ($nullAssignments -eq 0) { "  ✅ AssignmentName: 0 null records (PASS)" } else { "  ❌ AssignmentName: $nullAssignments null records ($([math]::Round($nullAssignments/$policyData.Count*100,1))%) (FAIL)" })
$(if ($nullDisplayNames -eq 0) { "  ✅ DisplayName: 0 null records (PASS)" } else { "  ⚠️  DisplayName: $nullDisplayNames null records ($([math]::Round($nullDisplayNames/$policyData.Count*100,1))%) (may be built-in policies)" })
$(if ($nullScopes -eq 0) { "  ✅ Scope: 0 null records (PASS)" } else { "  ❌ Scope: $nullScopes null records ($([math]::Round($nullScopes/$policyData.Count*100,1))%) (FAIL)" })
  
  SCOPE BREAKDOWN:
  - Subscription Scope: $subscriptionScoped assignments ($([math]::Round($subscriptionScoped/$policyData.Count*100,1))%)
  - Management Group Scope: $mgScoped assignments ($([math]::Round($mgScoped/$policyData.Count*100,1))%)
  - Resource Group Scope: $rgScoped assignments ($([math]::Round($rgScoped/$policyData.Count*100,1))%)
  
  ENFORCEMENT MODE:
  - Enforced (Default): $enforced assignments ($([math]::Round($enforced/$policyData.Count*100,1))%)
  - Not Enforced (DoNotEnforce): $notEnforced assignments ($([math]::Round($notEnforced/$policyData.Count*100,1))%)
  
  KEY VAULT POLICIES:
  - Total Key Vault-Related: $kvPolicies assignments
  - Unique Policy Types: $uniqueKVPolicies

VALIDATION SUMMARY:
$(if ($errors.Count -eq 0) { "  ✅ All critical fields validated successfully" } else { "  ❌ CRITICAL ERRORS FOUND: $($errors.Count)" })
$(if ($warnings.Count -gt 0) { "  ⚠️  WARNINGS: $($warnings.Count)" } else { "" })
  
$(if ($errors.Count -gt 0) {
@"
ERRORS:
$($errors | ForEach-Object { "  - $_" } | Out-String)
"@
} else { "" })

$(if ($warnings.Count -gt 0) {
@"
WARNINGS:
$($warnings | ForEach-Object { "  - $_" } | Out-String)
"@
} else { "" })

OVERALL STATUS: $overallStatus

========================================
Report generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
"@

$reportContent | Out-File -FilePath $OutputReport -Encoding UTF8 -Force

Write-Host "Validation report saved to: $OutputReport" -ForegroundColor Cyan
Write-Host ""

# Exit with appropriate code
if ($errors.Count -gt 0) {
    exit 1  # FAIL
} else {
    exit 0  # PASS
}
